#!/usr/bin/env bash

if [ ! -e "/etc/apt/sources.list.d/google.list" ]
then
	wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
	sudo sh -c 'echo "deb http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list'
fi
yes | sudo apt-get update
yes | sudo apt-get install -y google-chrome-stable

