#!/usr/bin/env bash

sudo apt-get update
sudo apt-get install -y copyq

configitem='X-GNOME-Autostart-Delay=3'
autostartfile=~/.config/autostart/copyq.desktop

grep -qxF $configitem $autostartfile || echo $configitem >> $autostartfile
