#!/bin/bash -i

sudo add-apt-repository -y ppa:hluk/copyq
sudo apt-get update
sudo apt-get install -y copyq

copyq config autostart true

configitem='X-GNOME-Autostart-Delay=3'
autostartfile=~/.config/autostart/copyq.desktop

grep -qxF $configitem $autostartfile || echo $configitem >> $autostartfile
